---
ansible_ssh_user: "lab"
ansible_ssh_pass: "juniper123"

contrail_keystone_address: "10.84.50.3"
contrail_admin_user: "admin"
contrail_admin_password: "password"

contrail_keepalived: no
contrail_haproxy_address: "10.84.50.1" # 10.84.50.80
contrail_netmask: "255.255.255.0"
contrail_prefixlen: "24"
contrail_gateway: "10.84.50.253"

contrail_router_asn: "64512"

contrail_tor_agents:
  - name: "test01"
    address: "10.84.50.81"
    ovs_protocol: "pssl"
    ovs_port: "9991"
    tunnel_address: "10.84.50.81"
    http_server_port: "9011"
    vendor_name: "Juniper"
    product_name: "QFX5100"
    tsn_names: [ "system002" ]
  - name: "test02"
    address: "10.84.50.82"
    ovs_protocol: "pssl"
    ovs_port: "9992"
    tunnel_address: "10.84.50.82"
    http_server_port: "9012"
    vendor_name: "Juniper"
    product_name: "QFX5100"
    tsn_names: [ "system002" ]
