---
- hosts: config
  sudo: yes
  tasks:
    - name: "provision config node"
      shell: "python /opt/contrail/utils/provision_config_node.py --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }} --oper add --admin_user admin --admin_password {{ contrail_admin_password }} --admin_tenant_name admin"

- hosts: database
  sudo: yes
  tasks:
    - name: "provision database node"
      shell: "python /opt/contrail/utils/provision_database_node.py --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }} --oper add --admin_user admin --admin_password {{ contrail_admin_password }} --admin_tenant_name admin"

- hosts: collector
  sudo: yes
  tasks:
    - name: "provision collector node"
      shell: "python /opt/contrail/utils/provision_analytics_node.py --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }} --oper add --admin_user admin --admin_password {{ contrail_admin_password }} --admin_tenant_name admin"

- hosts: control
  sudo: yes
  tasks:
    - name: "provision control node"
      shell: "python /opt/contrail/utils/provision_control.py --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --api_server_port 8082 --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }} --oper add --admin_user admin --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --router_asn 64512"

- hosts: config
  sudo: yes
  tasks:
    - name: "provision metadata services"
      shell: "python /opt/contrail/utils/provision_linklocal.py --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --oper add --admin_user admin --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --ipfabric_service_ip 10.84.50.1 --ipfabric_service_port 8775 --linklocal_service_name metadata --linklocal_service_ip 169.254.169.254 --linklocal_service_port 80"

- hosts: config
  sudo: yes
  tasks:
    - name: "provision encap"
      shell: "python /opt/contrail/utils/provision_encap.py --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --oper add --admin_user admin --admin_password {{ contrail_admin_password }} --encap_priority VXLAN,MPLSoUDP,MPLSoGRE"

- hosts: openstack
  sudo: yes
  tasks:
    - name: "fetch openstackrc temporary"
      fetch:
        src: "/etc/contrail/openstackrc"
        dest: "/tmp/tmp-openstackrc"
        flat: yes
      run_once: yes

- hosts: compute
  sudo: yes
  tasks:
    - name: "copy openstackrc"
      copy:
        src: "/tmp/tmp-openstackrc"
        dest: "/etc/contrail/openstackrc"

- hosts: openstack
  sudo: yes
  tasks:
    - name: "delete temporary openstackrc"
      local_action:
        module: "file"
        dest: "/tmp/tmp-openstackrc"
        state: "absent"
      run_once: yes
