---
- hosts: compute
  sudo: yes
  tasks:
    - name: "enable supervisor vrouter"
      file:
        path: "/etc/init/supervisor-vrouter.override"
        state: "absent"

    - include: -node-common.yml

    - name: "modify nova config"
      ini_file:
        dest: "/etc/nova/nova.conf"
        section: "DEFAULT"
        option: "neutron_admin_auth_url"
        value: "http://{{ hostvars[groups['openstack'][0]]['contrail_address'] }}:5000/v2.0/"

    - name: "modify nova config"
      replace:
        dest: "/etc/nova/nova.conf"
        regexp: "rpc_backend\\s*=\\s*nova.openstack.common.rpc.impl_qpid"
        replace: "#rpc_backend = nova.openstack.common.rpc.impl_qpid"

    - name: "check cgroup device acl in qemu conf"
      shell: "grep -q '^\\s*cgroup_device_acl' /etc/libvirt/qemu.conf"
      register: deviceacl
      ignore_errors: yes
      changed_when: no

    - name: "create cgroup device acl for qemu conf"
      template:
        src: "templates/qemu-device-acl-conf.j2"
        dest: "/tmp/qemu-device-acl.conf"
      when: deviceacl | failed

    - name: "combination of the qemu configuration"
      shell: "cat /tmp/qemu-device-acl.conf >> /etc/libvirt/qemu.conf"
      when: deviceacl | failed

    - name: "delete temporary configuration file"
      file:
        dest: "/tmp/qemu-device-acl.conf"
        state: "absent"
      when: deviceacl | failed

    - name: "fix up vrouter nodemgr param"
      template:
        src: "templates/vrouter-nodemgr-param.j2"
        dest: "/etc/contrail/vrouter_nodemgr_param"

    - name: "set contrail device name for ansible"
      set_fact:
        contrail_ansible_device: "ansible_{{ contrail_device }}"

    - name: "fix up default pmac"
      template:
        src: "templates/default-pmac.j2"
        dest: "/etc/contrail/default_pmac"

    - name: "copy agent param config from template"
      shell: "cp /etc/contrail/agent_param.tmpl /etc/contrail/agent_param"

    - name: "modify agent param config"
      lineinfile:
        dest: "/etc/contrail/agent_param"
        regexp: "dev=__DEVICE__"
        line: "dev={{ contrail_device }}"

    - name: "fix up contrail vrouter agent config"
      template:
        src: "templates/contrail-vrouter-agent-conf.j2"
        dest: "/etc/contrail/contrail-vrouter-agent.conf"

    - name: "delete lines for contrail interface"
      shell: "{{ item }}"
      with_items:
        - "sed -e '/auto {{ contrail_device }}/,$d' /etc/network/interfaces > /tmp/contrail-interfaces-top"
        - "sed -n -e '/auto {{ contrail_device }}/,$p' /etc/network/interfaces > /tmp/contrail-interfaces-bottom"
        - "sed -i -e '/auto {{ contrail_device }}/d' /tmp/contrail-interfaces-bottom"
        - "sed -i -n -e '/auto .*/,$p' /tmp/contrail-interfaces-bottom"
        - "cat /tmp/contrail-interfaces-top /tmp/contrail-interfaces-bottom > /etc/network/interfaces"

    - name: "delete lines for vrouter interface"
      shell: "{{ item }}"
      with_items:
        - "sed -e '/auto vhost0/,$d' /etc/network/interfaces > /tmp/contrail-interfaces-top"
        - "sed -n -e '/auto vhost0/,$p' /etc/network/interfaces > /tmp/contrail-interfaces-bottom"
        - "sed -i -e '/auto vhost0/d' /tmp/contrail-interfaces-bottom"
        - "sed -i -n -e '/auto .*/,$p' /tmp/contrail-interfaces-bottom"
        - "cat /tmp/contrail-interfaces-top /tmp/contrail-interfaces-bottom > /etc/network/interfaces"

    - name: "configure interface"
      lineinfile:
        dest: "/etc/network/interfaces"
        line: "{{ item }}"
        state: "present"
      with_items:
        - "auto {{ contrail_device }}"
        - "iface {{ contrail_device }} inet manual"
        - "\tpre-up ifconfig {{ contrail_device }} up"
        - "\tpost-down ifconfig {{ contrail_device }} down"
        - "auto vhost0"
        - "iface vhost0 inet static"
        - "\tpre-up /opt/contrail/bin/if-vhost0"
        - "\tnetwork_name application"
        - "\taddress {{ contrail_address }}"
        - "\tnetmask {{ contrail_netmask }}"

    - name: "delete temporary files"
      file:
        dest: "{{ item }}"
        state: "absent"
      with_items:
        - "/tmp/contrail-interfaces-top"
        - "/tmp/contrail-interfaces-bottom"

    - name: "fix up contrail vrouter nodemgr config"
      template:
        src: "templates/contrail-vrouter-nodemgr-conf.j2"
        dest: "/etc/contrail/contrail-vrouter-nodemgr.conf"

    - name: "fix up control details"
      lineinfile:
        dest: "/etc/contrail/ctrl-details"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: yes
      with_items:
        - { regexp: "^SERVICE_TENANT_NAME=", line: "SERVICE_TENANT_NAME=service" }
        - { regexp: "^SERVICE_TOKEN=", line: "SERVICE_TOKEN={{ contrail_service_token }}" }
        - { regexp: "^ADMIN_TOKEN=", line: "ADMIN_TOKEN={{ contrail_admin_password }}" }
        - { regexp: "^CONTROLLER=", line: "CONTROLLER={{ hostvars[groups['openstack'][0]]['contrail_address'] }}" }
        - { regexp: "^API_SERVER=", line: "API_SERVER={{ hostvars[groups['config'][0]]['contrail_address'] }}" }
        - { regexp: "^AMQP_SERVER=", line: "AMQP_SERVER={{ hostvars[groups['config'][0]]['contrail_address'] }}" }
        - { regexp: "^QUANTUM_PROTOCOL=", line: "QUANTUM_PROTOCOL=http" }
        - { regexp: "^QUANTUM=", line: "QUANTUM={{ hostvars[groups['config'][0]]['contrail_address'] }}" }
        - { regexp: "^QUANTUM_PORT=", line: "QUANTUM_PORT=9696" }
        - { regexp: "^AUTH_PROTOCOL=", line: "AUTH_PROTOCOL=http" }
        - { regexp: "^HYPERVISOR=", line: "HYPERVISOR=libvirt" }
        - { regexp: "^NOVA_PASSWORD=", line: "NOVA_PASSWORD={{ contrail_admin_password }}" }
        - { regexp: "^NEUTRON_PASSWORD=", line: "NEUTRON_PASSWORD={{ contrail_admin_password }}" }
        - { regexp: "^COMPUTE=", line: "COMPUTE={{ contrail_address }}" }
        - { regexp: "^CONTROLLER_MGMT=", line: "CONTROLLER_MGMT={{ hostvars[groups['openstack'][0]]['contrail_mgmt_address'] }}" }

    - name: "restart libvirt bin"
      service:
        name: "libvirt-bin"
        state: "restarted"

    - include: -vrouter-compute-setup.yml

    - name: "add vrouter to contrail"
      shell: "python /opt/contrail/utils/provision_vrouter.py --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }} --api_server_ip {{ hostvars[groups['config'][0]]['contrail_address'] }} --oper add --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --openstack_ip {{ hostvars[groups['openstack'][0]]['contrail_address'] }}"
