---
- hosts: all
  sudo: yes
  tasks:
    - name: "configure interface"
      lineinfile:
        dest: "/etc/network/interfaces"
        line: "{{ item }}"
      with_items:
        - "auto {{ contrail_device }}"
        - "iface {{ contrail_device }} inet static"
        - "\taddress {{ contrail_address }}"
        - "\tnetmask {{ contrail_netmask }}"

    - name: "set interface address"
      shell: "ifconfig {{ contrail_device }} {{ contrail_address }} netmask {{ contrail_netmask }}"

    - name: "up interface"
      shell: "ifconfig {{ contrail_device }} up"
