---
- hosts: config
  sudo: yes
  tasks:
    - name: "temporary disable supervisor config"
      template:
        src: "templates/override.j2"
        dest: "/etc/init/supervisor-config.override"

    - name: "temporary disable neutron server"
      template:
        src: "templates/override.j2"
        dest: "/etc/init/neutron-server.override"

    - name: "install contrail openstack config package"
      apt:
        name: "contrail-openstack-config"
