---
- hosts: tsn
  sudo: yes
  tasks:
    - name: "temporary disable supervisor vrouter"
      template:
        src: "templates/override.j2"
        dest: "/etc/init/supervisor-vrouter.override"

    - name: "install contrail vrouter dkms package"
      apt:
        name: "contrail-vrouter-dkms"

    - name: "install contrail vrouter common package"
      apt:
        name: "contrail-vrouter-common"

    - name: "install contrail nova vif package"
      apt:
        name: "contrail-nova-vif"
