---
- hosts: [compute, tsn]
  sudo: yes
  tasks:
    - name: "temporary disable supervisor vrouter"
      template:
        src: "templates/override.j2"
        dest: "/etc/init/supervisor-vrouter.override"

    - name: "install nova-compute for contrail package"
      apt:
        name: "nova-compute"
      when: install_nova

    - name: "install contrail vrouter 3.13.0-40 package"
      apt:
        name: "contrail-vrouter-3.13.0-40-generic"
      when: ansible_kernel == "3.13.0-40-generic"

    - name: "install contrail vrouter dkms package"
      apt:
        name: "contrail-vrouter-dkms"
      when: ansible_kernel != "3.13.0-40-generic"

    - name: "install contrail vrouter common package"
      apt:
        name: "contrail-vrouter-common"

    - name: "install contrail nova vif package"
      apt:
        name: "contrail-nova-vif"
